name: triage-to-project
on:
  issues:
    types: [opened]
jobs:
  add:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      projects: write
    steps:
      - name: Add issue to GitHub Project (v2)
        uses: actions/add-to-project@v1
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.PAT_SMD_PROJECT_REPO }}
          labeled: ""
          label-operator: OR
